/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package culturarte.graficos;

import culturarte.logica.DTColaborador;
import culturarte.logica.DTDireccion;
import culturarte.logica.DTProponente;
import culturarte.logica.DTUsuario;
import culturarte.logica.IControllerFactory;
import culturarte.logica.IController;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.*;
import java.nio.file.*;
import javax.swing.JOptionPane;

 
public class AltaUsuario extends javax.swing.JInternalFrame {
    private IController controller;
    private static final String CARPETA_IMAGENES = System.getProperty("user.dir") + File.separator + "imagenesUsuarios" + File.separator;
    private String rutaImagenUsuario;
    /**
     * Creates new form Alta
     */
    public AltaUsuario() {
        IControllerFactory fabrica = IControllerFactory.getInstance();
        this.controller = fabrica.getIController();
        
        
        initComponents();
    }

    
    
    private String obtenerExtension(String nombreArchivo) {
        int i = nombreArchivo.lastIndexOf('.');
        if (i > 0) {
            return nombreArchivo.substring(i + 1);
        }
        return "png";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoNickname = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        campoNombre = new javax.swing.JTextField();
        campoApellido = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botonAddImagen = new javax.swing.JButton();
        radioProponente = new javax.swing.JRadioButton();
        radioColaborador = new javax.swing.JRadioButton();
        panelProponente = new javax.swing.JPanel();
        labelProponente = new javax.swing.JLabel();
        labelCiudad = new javax.swing.JLabel();
        labelCalle = new javax.swing.JLabel();
        labelNumPuerta = new javax.swing.JLabel();
        campoCiudad = new javax.swing.JTextField();
        campoCalle = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaBiografia = new javax.swing.JTextArea();
        labelBiografia = new javax.swing.JLabel();
        campoSitioWeb = new javax.swing.JTextField();
        labelSitioWeb = new javax.swing.JLabel();
        campoNumPuerta = new javax.swing.JFormattedTextField();
        labelImagen = new javax.swing.JLabel();
        campoFNac = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registrar un Usuario");
        setRequestFocusEnabled(false);

        jLabel1.setText("Nickname:");

        jLabel2.setText("Nombre:");

        campoNickname.setColumns(8);
        campoNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNicknameActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        campoNombre.setColumns(8);
        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        campoApellido.setColumns(8);
        campoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApellidoActionPerformed(evt);
            }
        });

        campoEmail.setColumns(8);
        campoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEmailActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellido:");

        jLabel4.setText("E-Mail:");

        jLabel5.setText("Fecha de Nacimiento:");

        botonAddImagen.setText("Seleccionar Imagen");
        botonAddImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAddImagenActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioProponente);
        radioProponente.setText("Proponente");
        radioProponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioProponenteActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioColaborador);
        radioColaborador.setText("Colaborador");
        radioColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioColaboradorActionPerformed(evt);
            }
        });

        labelProponente.setText("Datos Proponente");
        labelProponente.setEnabled(false);

        labelCiudad.setText("Ciudad:");
        labelCiudad.setEnabled(false);

        labelCalle.setText("Calle:");
        labelCalle.setEnabled(false);

        labelNumPuerta.setText("Nº Puerta:");
        labelNumPuerta.setEnabled(false);

        campoCiudad.setEnabled(false);
        campoCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCiudadActionPerformed(evt);
            }
        });

        campoCalle.setEnabled(false);

        areaBiografia.setColumns(18);
        areaBiografia.setLineWrap(true);
        areaBiografia.setRows(4);
        areaBiografia.setEnabled(false);
        jScrollPane1.setViewportView(areaBiografia);

        labelBiografia.setText("Biografía:");
        labelBiografia.setEnabled(false);

        campoSitioWeb.setEnabled(false);
        campoSitioWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSitioWebActionPerformed(evt);
            }
        });

        labelSitioWeb.setText("Sitio Web:");
        labelSitioWeb.setEnabled(false);

        campoNumPuerta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        campoNumPuerta.setEnabled(false);

        javax.swing.GroupLayout panelProponenteLayout = new javax.swing.GroupLayout(panelProponente);
        panelProponente.setLayout(panelProponenteLayout);
        panelProponenteLayout.setHorizontalGroup(
            panelProponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProponenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProponenteLayout.createSequentialGroup()
                        .addGroup(panelProponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCiudad)
                            .addComponent(labelCalle)
                            .addComponent(labelNumPuerta))
                        .addGroup(panelProponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProponenteLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(labelProponente)
                                .addGap(67, 67, 67))
                            .addGroup(panelProponenteLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelProponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoCiudad, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(campoCalle)
                                    .addComponent(campoNumPuerta))
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProponenteLayout.createSequentialGroup()
                        .addGroup(panelProponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoSitioWeb, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(panelProponenteLayout.createSequentialGroup()
                        .addGroup(panelProponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelBiografia)
                            .addComponent(labelSitioWeb))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelProponenteLayout.setVerticalGroup(
            panelProponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProponenteLayout.createSequentialGroup()
                .addComponent(labelProponente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCiudad)
                    .addComponent(campoCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCalle)
                    .addComponent(campoCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumPuerta)
                    .addComponent(campoNumPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(labelBiografia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(labelSitioWeb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoSitioWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        labelImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImagen.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        campoFNac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/y"))));
        campoFNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFNacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonAddImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoNickname, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(campoNombre)
                                    .addComponent(campoApellido)
                                    .addComponent(campoEmail)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(radioColaborador)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(radioProponente)
                                        .addGap(17, 17, 17))
                                    .addComponent(campoFNac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelProponente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonCancelar)
                        .addGap(45, 45, 45)
                        .addComponent(botonAceptar)
                        .addGap(21, 21, 21)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelProponente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonCancelar)
                            .addComponent(botonAceptar))
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(campoNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(campoFNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioProponente)
                            .addComponent(radioColaborador))
                        .addGap(39, 39, 39)
                        .addComponent(botonAddImagen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void campoNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNicknameActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void campoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApellidoActionPerformed

    private void campoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEmailActionPerformed

    private void botonAddImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAddImagenActionPerformed
        JFileChooser selectorImagen = new JFileChooser();
        String[] tiposImagen = {"jpg", "png"};
        FileNameExtensionFilter filtroImagen = new FileNameExtensionFilter("Archivos .jpg o .png", tiposImagen);
        selectorImagen.setFileFilter(filtroImagen);
        selectorImagen.setAcceptAllFileFilterUsed(false);

        int resultado = selectorImagen.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivoElegido = selectorImagen.getSelectedFile();
            try {
                String extensionImagen = tipoImagen(archivoElegido);

                if (extensionImagen.equals("jpg") || extensionImagen.equals("png")) {
                    BufferedImage temp = ImageIO.read(archivoElegido);

                    File carpetaImagenes = new File("imagenesUsuarios");
                    if (!carpetaImagenes.exists()) {
                        carpetaImagenes.mkdirs();
                    }

                    String nombreArchivo = System.currentTimeMillis() + "." + extensionImagen;
                    File archivoDestino = new File(carpetaImagenes, nombreArchivo);
                    ImageIO.write(temp, extensionImagen, archivoDestino);

                    this.rutaImagenUsuario = nombreArchivo;

                    Image imagenEscalada = temp.getScaledInstance(133, 133, Image.SCALE_SMOOTH);
                    this.labelImagen.setIcon(new ImageIcon(imagenEscalada));
                }
            } catch (IOException ex) {
                System.getLogger(AltaUsuario.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    }//GEN-LAST:event_botonAddImagenActionPerformed
    private String tipoImagen(File archivo) throws IOException {
        Path path = archivo.toPath();
        String mimeType = Files.probeContentType(path);
        if (mimeType != null) {
            if (mimeType.equals("image/png")) {
                return "png";
            } else if (mimeType.equals("image/jpeg")) {
                return "jpg";
            }
        }
        return "desconocido";
    }
        
    private void radioProponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioProponenteActionPerformed
        enableDatosProponente();
    }//GEN-LAST:event_radioProponenteActionPerformed

    private void enableDatosProponente() {
        this.labelProponente.setEnabled(true);
        this.labelCiudad.setEnabled(true);
        this.campoCiudad.setEnabled(true);
        this.labelCalle.setEnabled(true);
        this.campoCalle.setEnabled(true);
        this.labelNumPuerta.setEnabled(true);
        this.campoNumPuerta.setEnabled(true);
        this.labelBiografia.setEnabled(true);
        this.areaBiografia.setEnabled(true);
        this.labelSitioWeb.setEnabled(true);
        this.campoSitioWeb.setEnabled(true);
    }
    
    private void campoCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCiudadActionPerformed

    private void campoSitioWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSitioWebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSitioWebActionPerformed

    private void radioColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioColaboradorActionPerformed
        disableDatosProponente();
    }//GEN-LAST:event_radioColaboradorActionPerformed

    private void disableDatosProponente() {
        this.labelProponente.setEnabled(false);
        this.labelCiudad.setEnabled(false);
        this.campoCiudad.setEnabled(false);
        this.labelCalle.setEnabled(false);
        this.campoCalle.setEnabled(false);
        this.labelNumPuerta.setEnabled(false);
        this.campoNumPuerta.setEnabled(false);
        this.labelBiografia.setEnabled(false);
        this.areaBiografia.setEnabled(false);
        this.labelSitioWeb.setEnabled(false);
        this.campoSitioWeb.setEnabled(false);
    }
    
    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        if (sonValidosLosCampos()) {
            String nick = this.campoNickname.getText();
            String nombre = this.campoNombre.getText();
            String apellido = this.campoApellido.getText();
            String email = this.campoEmail.getText();
            Date fecha = (Date) this.campoFNac.getValue();
            LocalDate fechaNac = fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            
            DTUsuario user = null;
            if (this.radioColaborador.isSelected()) {
                user = new DTColaborador(nick, nombre, apellido, email, fechaNac, this.rutaImagenUsuario);
            } else if (this.radioProponente.isSelected()) {
                String ciudad = this.campoCiudad.getText();
                String calle = this.campoCiudad.getText();
                int numPuerta = Integer.parseInt(this.campoNumPuerta.getText());
                DTDireccion direccion = new DTDireccion(ciudad, calle, numPuerta);
                String biografia = this.areaBiografia.getText();
                String sitioWeb = this.campoSitioWeb.getText();
                
                user = new DTProponente(direccion, biografia, sitioWeb, nick, nombre, apellido, email, fechaNac, this.rutaImagenUsuario);
            }
            this.controller.addUsuario(user);  
        } else {
            return;
        }
        this.dispose();
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void campoFNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFNacActionPerformed

    private boolean sonValidosLosCampos() {
        if (!(this.radioColaborador.isSelected() || this.radioProponente.isSelected())) {
            return false;
        }
        if (!sonValidosCamposBase()) {
            return false;
        }
        if (this.radioProponente.isSelected()) {
            if (!sonValidosCamposProponente()) {
                return false;
            }
        }
        return true;
    }
    
    private boolean sonValidosCamposBase() {
        boolean ret = true;
        if (this.campoNickname.getText().isBlank()) {
            ret = false;
        } else if (this.campoNombre.getText().isBlank()) {
            ret = false;
        } else if (this.campoApellido.getText().isBlank()) {
            ret = false;
        } else if (this.campoEmail.getText().isBlank()) {
            ret = false;
        } else if (this.campoFNac.getText().isBlank()) {
            ret = false;
        }
        return ret;
    }
    
    private boolean sonValidosCamposProponente() {
        boolean ret = true;
        if (this.campoCiudad.getText().isBlank()) {
            ret = false;
        } else if (this.campoCalle.getText().isBlank()) {
            ret = false;
        } else if (this.campoNumPuerta.getText().isBlank()) {
            ret = false;
        }
        return ret;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaBiografia;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonAddImagen;
    private javax.swing.JButton botonCancelar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JTextField campoCalle;
    private javax.swing.JTextField campoCiudad;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JFormattedTextField campoFNac;
    private javax.swing.JTextField campoNickname;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JFormattedTextField campoNumPuerta;
    private javax.swing.JTextField campoSitioWeb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBiografia;
    private javax.swing.JLabel labelCalle;
    private javax.swing.JLabel labelCiudad;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JLabel labelNumPuerta;
    private javax.swing.JLabel labelProponente;
    private javax.swing.JLabel labelSitioWeb;
    private javax.swing.JPanel panelProponente;
    private javax.swing.JRadioButton radioColaborador;
    private javax.swing.JRadioButton radioProponente;
    // End of variables declaration//GEN-END:variables
}
