/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package culturarte.graficos;
import culturarte.logica.IControllerFactory;
import culturarte.logica.IController;
import javax.swing.tree.DefaultMutableTreeNode;
/**
 *
 * @author kevin
 */
public class AltaPropuesta extends javax.swing.JInternalFrame {

    private IController controller;
    
public AltaPropuesta() {
    IControllerFactory fabrica = IControllerFactory.getInstance();
    this.controller = fabrica.getIController();
    initComponents();

    // Listener para JList
    listaProponentes.addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            String select1 = listaProponentes.getSelectedValue();
            DefaultMutableTreeNode select2 = (DefaultMutableTreeNode) arbolEspectaculo.getLastSelectedPathComponent();

            if (select1 != null && select2 != null) {
                enableDatosPropuesta();
            }
        }
    });

    // Listener para JTree
    arbolEspectaculo.getSelectionModel().addTreeSelectionListener(e -> {
        String select1 = listaProponentes.getSelectedValue();
        DefaultMutableTreeNode select2 = (DefaultMutableTreeNode) arbolEspectaculo.getLastSelectedPathComponent();

        if (select1 != null && select2 != null) {
            enableDatosPropuesta();
        }
    });
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        botonAceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProponentes = new javax.swing.JList<>(this.controller.listarProponentes().toArray(new String[0]));
        Proponentes = new javax.swing.JLabel();
        Tipo_de_Espectaculo = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        NombreL = new javax.swing.JLabel();
        DescripcionL = new javax.swing.JLabel();
        ImagenL = new javax.swing.JButton();
        LugarL = new javax.swing.JLabel();
        Lugar = new javax.swing.JTextField();
        Fecha_realizarL = new javax.swing.JLabel();
        Fecha_realizar = new javax.swing.JTextField();
        PrecioEntradaL = new javax.swing.JLabel();
        Precio_entrada = new javax.swing.JTextField();
        MontoReunirL = new javax.swing.JLabel();
        Monto_reunir = new javax.swing.JTextField();
        FechaPubliL = new javax.swing.JLabel();
        FechaPubli = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Descripcion = new javax.swing.JTextArea();
        Nombre = new javax.swing.JTextField();
        arbolEspectaculo = new javax.swing.JTree(this.controller.listarCategorias());

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Alta de Propuesta");
        setPreferredSize(new java.awt.Dimension(1000, 500));

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listaProponentes);

        Proponentes.setText("Proponentes");

        Tipo_de_Espectaculo.setText("Tipo de Espectaculo");

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        NombreL.setText("Nombre:");
        NombreL.setEnabled(false);

        DescripcionL.setText("Descripcion:");
        DescripcionL.setEnabled(false);

        ImagenL.setText("Seleccionar Imagen");
        ImagenL.setEnabled(false);
        ImagenL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImagenLActionPerformed(evt);
            }
        });

        LugarL.setText("Lugar:");
        LugarL.setEnabled(false);

        Lugar.setEnabled(false);
        Lugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LugarActionPerformed(evt);
            }
        });

        Fecha_realizarL.setText("Fecha a Realizar:");
        Fecha_realizarL.setEnabled(false);

        Fecha_realizar.setEnabled(false);

        PrecioEntradaL.setText("Precio entrada:");
        PrecioEntradaL.setEnabled(false);

        Precio_entrada.setEnabled(false);

        MontoReunirL.setText("Monto a Reunir:");
        MontoReunirL.setEnabled(false);

        Monto_reunir.setEnabled(false);

        FechaPubliL.setText("Fecha de Publicacion:");
        FechaPubliL.setEnabled(false);

        FechaPubli.setEnabled(false);

        jScrollPane3.setEnabled(false);

        Descripcion.setColumns(20);
        Descripcion.setRows(5);
        Descripcion.setEnabled(false);
        jScrollPane3.setViewportView(Descripcion);

        Nombre.setEnabled(false);
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Proponentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(48, 48, 48)
                        .addComponent(Tipo_de_Espectaculo))
                    .addComponent(arbolEspectaculo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(botonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonAceptar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DescripcionL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ImagenL)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(FechaPubliL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FechaPubli, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(PrecioEntradaL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Precio_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(NombreL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Fecha_realizarL)
                                            .addComponent(LugarL, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MontoReunirL)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Lugar, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                        .addComponent(Fecha_realizar))
                                    .addComponent(Monto_reunir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(179, 179, 179))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Proponentes, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tipo_de_Espectaculo))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(NombreL)
                                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(FechaPubli, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(FechaPubliL))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(PrecioEntradaL)
                                            .addComponent(Precio_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(LugarL)
                                            .addComponent(Lugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Fecha_realizarL)
                                            .addComponent(Fecha_realizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(MontoReunirL)
                                            .addComponent(Monto_reunir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DescripcionL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ImagenL))
                            .addComponent(arbolEspectaculo, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonCancelar))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
 

    
    
    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        String user = listaProponentes.getSelectedValue();
        
        
        if(user==null){
            setTitle("Proponente no selecionado");
        }
      
        if(user != null  ){
            setTitle("lol");
         
           
            this.controller.addPropuesta();
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.dispose();       
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void ImagenLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImagenLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImagenLActionPerformed

    private void LugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LugarActionPerformed
    
    
    private void enableDatosPropuesta(){
        this.Descripcion.setEnabled(true);
        this.DescripcionL.setEnabled(true);
        this.FechaPubli.setEnabled(true);
        this.FechaPubliL.setEnabled(true);
        this.Fecha_realizar.setEnabled(true);
        this.Fecha_realizarL.setEnabled(true);
        this.ImagenL.setEnabled(true);
        this.Lugar.setEnabled(true);
        this.LugarL.setEnabled(true);
        this.MontoReunirL.setEnabled(true);
        this.Nombre.setEnabled(true);
        this.NombreL.setEnabled(true);
        this.PrecioEntradaL.setEnabled(true);
        this.Precio_entrada.setEnabled(true);
        this.Monto_reunir.setEnabled(true);
        
    }
    
     private void disableDatosPropuesta(){
        this.Descripcion.setEnabled(false);
        this.DescripcionL.setEnabled(false);
        this.FechaPubli.setEnabled(false);
        this.FechaPubliL.setEnabled(false);
        this.Fecha_realizar.setEnabled(false);
        this.Fecha_realizarL.setEnabled(false);
        this.ImagenL.setEnabled(false);
        this.Lugar.setEnabled(false);
        this.LugarL.setEnabled(false);
        this.MontoReunirL.setEnabled(false);
        this.Nombre.setEnabled(false);
        this.NombreL.setEnabled(false);
        this.PrecioEntradaL.setEnabled(false);
        this.Precio_entrada.setEnabled(false);
        this.Descripcion.setEnabled(false);
    }
    
    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Descripcion;
    private javax.swing.JLabel DescripcionL;
    private javax.swing.JTextField FechaPubli;
    private javax.swing.JLabel FechaPubliL;
    private javax.swing.JTextField Fecha_realizar;
    private javax.swing.JLabel Fecha_realizarL;
    private javax.swing.JButton ImagenL;
    private javax.swing.JTextField Lugar;
    private javax.swing.JLabel LugarL;
    private javax.swing.JLabel MontoReunirL;
    private javax.swing.JTextField Monto_reunir;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel NombreL;
    private javax.swing.JLabel PrecioEntradaL;
    private javax.swing.JTextField Precio_entrada;
    private javax.swing.JLabel Proponentes;
    private javax.swing.JLabel Tipo_de_Espectaculo;
    private javax.swing.JTree arbolEspectaculo;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listaProponentes;
    // End of variables declaration//GEN-END:variables
}
