/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package culturarte.graficos;
import culturarte.logica.IController;
import culturarte.logica.IControllerFactory;
import javax.swing.DefaultListModel;

/**
 *
 * @author alexi
 */
public class DejarDeSeguirUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form DejarDeSeguirUsuario
     */
    private IController controller;
    public DejarDeSeguirUsuario() {
             IControllerFactory fabrica = IControllerFactory.getInstance();
         this.controller = fabrica.getIController();
         
    initComponents();
        DefaultListModel<String> modelo = (DefaultListModel<String>) listaSeguidores.getModel();
        modelo.clear();
        for(String nick : controller.listarUsuarios()){
            modelo.addElement(nick);
        }
         listaSeguidores.addListSelectionListener(e ->{
          if (!e.getValueIsAdjusting()) {
            String seleccionado = listaSeguidores.getSelectedValue();
              if(seleccionado!= null){
              DefaultListModel<String> modelo1 = (DefaultListModel<String>) listaUsuariosSiguiendo.getModel();
                modelo1.clear();
                for (String nick1 : controller.listarUsuariosSiguiendo(seleccionado)) {
                    modelo1.addElement(nick1);
                }
              }
              String selected2 = listaUsuariosSiguiendo.getSelectedValue();
              if(seleccionado != null && selected2 != null){
                  enableAceptar();
              }
              else{
                  disableAceptar();
              }
      }
    });
      listaUsuariosSiguiendo.addListSelectionListener(e ->{
          String seleccionado = listaSeguidores.getSelectedValue();
          String selected2 = listaUsuariosSiguiendo.getSelectedValue();
          if(seleccionado!= null && selected2 != null){
              enableAceptar();
          }
          else{
                  disableAceptar();
              }
      });
    }
    private void enableAceptar(){
      this.botonAceptar.setEnabled(true);
    }
    private void disableAceptar(){
      this.botonAceptar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaSeguidores = listaSeguidores = new javax.swing.JList<>(new javax.swing.DefaultListModel<>());
        jScrollPane2 = new javax.swing.JScrollPane();
        listaUsuariosSiguiendo = listaUsuariosSiguiendo = new javax.swing.JList<>(new javax.swing.DefaultListModel<>());
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Dejar de seguir usuario");

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.setEnabled(false);
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listaSeguidores);

        jScrollPane2.setViewportView(listaUsuariosSiguiendo);

        jLabel1.setText("Seguidor:");

        jLabel2.setText("Usuario que sigue:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonAceptar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        String seguidor = this.listaSeguidores.getSelectedValue();
        String usuarioSiguiendo = this.listaUsuariosSiguiendo.getSelectedValue();
        this.controller.dejarDeSeguirUsuario(seguidor,usuarioSiguiendo);
        this.dispose();
    }//GEN-LAST:event_botonAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaSeguidores;
    private javax.swing.JList<String> listaUsuariosSiguiendo;
    // End of variables declaration//GEN-END:variables
}
