/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package culturarte.graficos;

import culturarte.logica.DTPropuesta;
import culturarte.logica.IController;
import culturarte.logica.IControllerFactory;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author faxcundo
 */
public class ModificarPropuesta extends javax.swing.JInternalFrame {

    private IController controller;

    public ModificarPropuesta() {
        IControllerFactory fabrica = IControllerFactory.getInstance();
        this.controller = fabrica.getIController();
        initComponents();
        controller.listarPropuestas();
        DefaultListModel<String> modelo = (DefaultListModel<String>) ListaPropuestas.getModel();
        modelo.clear();
        for (String prop : controller.listarPropuestas()) {
            modelo.addElement(prop);
        }

        ListaPropuestas.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                String selec = ListaPropuestas.getSelectedValue();
                if (selec != null) {
                    enableCampos();
                    DTPropuesta dtprop = controller.obtenerDTPropuesta(selec);
                    this.descripcion.setText(dtprop.getDescripcion());
                    this.categoria.setText(dtprop.getTipoPropuesta());
                    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                    LocalDate fechaRealizar = dtprop.getFechaRealizara();
                    this.fecharealizar.setText(fechaRealizar.format(formatter));
                    LocalDate fechaPubli = dtprop.getFechaPublicacion();
                    if (fechaPubli == null) {
                        this.fechapublicacion.setText("");
                    } else {
                        this.fechapublicacion.setText(fechaPubli.format(formatter));
                    }
                    this.lugar.setText(dtprop.getLugarRealizara());
                    this.montoreunir.setText(Float.toString(dtprop.getMontoAReunir()));
                    ModificarPropuesta.this.precioentrada.setText(Float.toString(dtprop.getPrecioEntrada()));
                    //AGREGAR IMAGEN CUANDO SE CAMBIE
                    

                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void enableCampos() {
        this.descripcion.setEnabled(true);
        this.categoria.setEnabled(true);
        this.fecharealizar.setEnabled(true);
        this.fechapublicacion.setEnabled(true);
        this.lugar.setEnabled(true);
        this.montoreunir.setEnabled(true);
        this.precioentrada.setEnabled(true);
        this.Aceptar.setEnabled(true);

    }
    
   private boolean sonValidosLosCampos(){
        
        if(this.descripcion.getText().isBlank()){
            return false;
        }
        if(this.categoria.getText().isBlank()){
            return false;
        }
        if(this.fecharealizar.getText().isBlank()){
            return false;
        }
        if(this.fechapublicacion.getText().isBlank()){
            return false;
        }
        if(this.lugar.getText().isBlank()){
            return false;
        }
        if(this.montoreunir.getText().isBlank()){
            return false;
        }
        if(this.precioentrada.getText().isBlank()){
            return false;
        }   
        return true;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Aceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaPropuestas = new javax.swing.JList<>(new javax.swing.DefaultListModel<>());
        labelFechaPublicacion = new javax.swing.JLabel();
        labelImagen = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        labelMontoReunir = new javax.swing.JLabel();
        labelCategoria = new javax.swing.JLabel();
        labelLugar = new javax.swing.JLabel();
        labelFechaRealizar = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        lugar = new javax.swing.JTextField();
        fecharealizar = new javax.swing.JTextField();
        precioentrada = new javax.swing.JTextField();
        montoreunir = new javax.swing.JTextField();
        fechapublicacion = new javax.swing.JTextField();
        categoria = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        labelImagen1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(650, 370));

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Aceptar.setText("Aceptar");
        Aceptar.setEnabled(false);
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(ListaPropuestas);

        labelFechaPublicacion.setText("Fecha de publicación:");

        labelDescripcion.setText("Descripción:");

        labelMontoReunir.setText("Monto a reunir:");

        labelCategoria.setText("Categoría:");

        labelLugar.setText("Lugar a realizar:");

        labelFechaRealizar.setText("Fecha a realizar:");

        labelPrecio.setText("Precio de entrada:");

        lugar.setEnabled(false);

        fecharealizar.setEnabled(false);

        precioentrada.setEnabled(false);

        montoreunir.setEnabled(false);

        fechapublicacion.setEnabled(false);

        categoria.setEnabled(false);

        jScrollPane2.setEnabled(false);

        descripcion.setColumns(20);
        descripcion.setRows(5);
        descripcion.setEnabled(false);
        jScrollPane2.setViewportView(descripcion);

        jLabel1.setText("Propuestas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(labelImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelMontoReunir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelFechaRealizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelFechaPublicacion))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lugar)
                                .addComponent(fecharealizar)
                                .addComponent(precioentrada)
                                .addComponent(montoreunir)
                                .addComponent(fechapublicacion)
                                .addComponent(categoria)))
                        .addComponent(jScrollPane2)))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDescripcion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelLugar))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(fecharealizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelFechaRealizar)))
                                    .addComponent(labelImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(precioentrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelPrecio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(montoreunir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelMontoReunir))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechapublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFechaPublicacion))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Aceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        if(sonValidosLosCampos()){
            String x = this.ListaPropuestas.getSelectedValue();
            //DTPropuesta dtp = new DTPropuesta(this.ListaPropuestas.getSelectedValue(),this.descripcion.getText(),this.);
            
            
        }
    }//GEN-LAST:event_AceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JList<String> ListaPropuestas;
    private javax.swing.JTextField categoria;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JTextField fechapublicacion;
    private javax.swing.JTextField fecharealizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelFechaPublicacion;
    private javax.swing.JLabel labelFechaRealizar;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JLabel labelImagen1;
    private javax.swing.JLabel labelLugar;
    private javax.swing.JLabel labelMontoReunir;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JTextField lugar;
    private javax.swing.JTextField montoreunir;
    private javax.swing.JTextField precioentrada;
    // End of variables declaration//GEN-END:variables
}
