/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package culturarte.graficos;

import culturarte.logica.DTPropuesta;
import culturarte.logica.IController;
import culturarte.logica.IControllerFactory;
import culturarte.logica.TipoRetorno;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.text.DecimalFormatSymbols;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author mark
 */
public class RegistrarColaboracion extends javax.swing.JInternalFrame {

    private IController controller;

    /**
     * Creates new form RegistrarColaboracion
     */
    public RegistrarColaboracion() {
        IControllerFactory fabrica = IControllerFactory.getInstance();
        this.controller = fabrica.getIController();

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPropuestaProponente = new javax.swing.JList<>(this.controller.listarPropuestasProponentes().toArray(new String[0]));
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaColaboradores = new javax.swing.JList<>(this.controller.listarColaboradores().toArray(new String[0]));
        jLabel2 = new javax.swing.JLabel();
        datosPropuesta = new javax.swing.JPanel();
        labelImagen = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaDescripcion = new javax.swing.JTextArea();
        labelDescripcion = new javax.swing.JLabel();
        campoLugar = new javax.swing.JTextField();
        labelLugar = new javax.swing.JLabel();
        campoFechaRealizar = new javax.swing.JTextField();
        labelFechaRealizar = new javax.swing.JLabel();
        campoPrecio = new javax.swing.JTextField();
        labelPrecio = new javax.swing.JLabel();
        campoMontoReunir = new javax.swing.JTextField();
        labelMontoReunir = new javax.swing.JLabel();
        campoFechaPublicacion = new javax.swing.JTextField();
        labelFechaPublicacion = new javax.swing.JLabel();
        campoCategoria = new javax.swing.JTextField();
        labelCategoria = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        comboRetorno = new javax.swing.JComboBox<>();
        campoMontoColab = new javax.swing.JFormattedTextField();
        labelRetorno = new javax.swing.JLabel();
        labelMontoColab = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registrar colaboración");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        listaPropuestaProponente.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaPropuestaProponenteValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaPropuestaProponente);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Propuesta - Proponente");

        jScrollPane2.setViewportView(listaColaboradores);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Colaborador");

        areaDescripcion.setEditable(false);
        areaDescripcion.setColumns(20);
        areaDescripcion.setLineWrap(true);
        areaDescripcion.setRows(5);
        areaDescripcion.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(areaDescripcion);

        labelDescripcion.setText("Descripción:");

        campoLugar.setEditable(false);
        campoLugar.setCaretColor(new java.awt.Color(255, 255, 255));

        labelLugar.setText("Lugar a realizar:");

        campoFechaRealizar.setEditable(false);
        campoFechaRealizar.setCaretColor(new java.awt.Color(255, 255, 255));

        labelFechaRealizar.setText("Fecha a realizar:");

        campoPrecio.setEditable(false);
        campoPrecio.setCaretColor(new java.awt.Color(255, 255, 255));

        labelPrecio.setText("Precio de entrada:");

        campoMontoReunir.setEditable(false);
        campoMontoReunir.setCaretColor(new java.awt.Color(255, 255, 255));

        labelMontoReunir.setText("Monto a reunir:");

        campoFechaPublicacion.setEditable(false);
        campoFechaPublicacion.setCaretColor(new java.awt.Color(255, 255, 255));

        labelFechaPublicacion.setText("Fecha de publicación:");

        campoCategoria.setEditable(false);
        campoCategoria.setCaretColor(new java.awt.Color(255, 255, 255));

        labelCategoria.setText("Categoría:");

        javax.swing.GroupLayout datosPropuestaLayout = new javax.swing.GroupLayout(datosPropuesta);
        datosPropuesta.setLayout(datosPropuestaLayout);
        datosPropuestaLayout.setHorizontalGroup(
            datosPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosPropuestaLayout.createSequentialGroup()
                .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(datosPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3)
                    .addGroup(datosPropuestaLayout.createSequentialGroup()
                        .addGroup(datosPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelFechaPublicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelMontoReunir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelFechaRealizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelLugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(datosPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(datosPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(datosPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(datosPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(datosPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(datosPropuestaLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(campoLugar))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosPropuestaLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(campoFechaRealizar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosPropuestaLayout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosPropuestaLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(campoMontoReunir, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosPropuestaLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(campoFechaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosPropuestaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(campoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(37, 37, 37))
        );
        datosPropuestaLayout.setVerticalGroup(
            datosPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosPropuestaLayout.createSequentialGroup()
                .addGroup(datosPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(datosPropuestaLayout.createSequentialGroup()
                        .addComponent(labelDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(datosPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelLugar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(datosPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoFechaRealizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFechaRealizar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(datosPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPrecio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(datosPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoMontoReunir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMontoReunir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(datosPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoFechaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFechaPublicacion))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datosPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCategoria))
                .addGap(0, 39, Short.MAX_VALUE))
        );

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        comboRetorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRetornoActionPerformed(evt);
            }
        });

        campoMontoColab.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0.00", new DecimalFormatSymbols(Locale.US)))));
        campoMontoColab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMontoColabActionPerformed(evt);
            }
        });

        labelRetorno.setText("Tipo de retorno:");

        labelMontoColab.setText("Monto a colaborar:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboRetorno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelRetorno, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoMontoColab)
                    .addComponent(labelMontoColab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRetorno)
                    .addComponent(labelMontoColab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoMontoColab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCancelar)
                .addGap(132, 132, 132)
                .addComponent(botonAceptar)
                .addGap(43, 43, 43))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(datosPropuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(datosPropuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonAceptar))
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboRetornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRetornoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRetornoActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void listaPropuestaProponenteValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaPropuestaProponenteValueChanged
        String tituloProp = this.listaPropuestaProponente.getSelectedValue();
        int primerEspacio = tituloProp.indexOf(' ');
        if (primerEspacio != -1) {
            tituloProp = tituloProp.substring(0, primerEspacio);
        }
        DTPropuesta datosProp = this.controller.obtenerDTPropuesta(tituloProp);

        this.areaDescripcion.setText(datosProp.getDescripcion());
        this.campoLugar.setText(datosProp.getLugarRealizara());

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate fechaRealizar = datosProp.getFechaRealizara();
        this.campoFechaRealizar.setText(fechaRealizar.format(formatter));
        this.campoPrecio.setText(Float.toString(datosProp.getPrecioEntrada()));
        this.campoMontoReunir.setText(Float.toString(datosProp.getMontoAReunir()));
        LocalDate fechaPublicacion = datosProp.getFechaPublicacion();
        this.campoFechaPublicacion.setText(fechaPublicacion.format(formatter));
        this.campoCategoria.setText(datosProp.getTipoPropuesta());
        cargarRetornosCombo(datosProp.getTiposRetorno());
        cargarImagenLabel(datosProp.getImagen());

    }//GEN-LAST:event_listaPropuestaProponenteValueChanged

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        if (sonValidosLosCampos()) {
            String nickColab = this.listaColaboradores.getSelectedValue();
            String tituloProp = cortarTituloProp(this.listaPropuestaProponente.getSelectedValue());
            float montoColab = Float.parseFloat(this.campoMontoColab.getText());
            String tipoRetorno = this.comboRetorno.getSelectedItem().toString();
            this.controller.realizarColaboracion(nickColab, tituloProp, montoColab, tipoRetorno);

            this.dispose();
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void campoMontoColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMontoColabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMontoColabActionPerformed

    private String cortarTituloProp(String tituloProp) {
        int primerEspacio = tituloProp.indexOf(' ');
        if (primerEspacio != -1) {
            tituloProp = tituloProp.substring(0, primerEspacio);
        }
        return tituloProp;
    }

    private boolean sonValidosLosCampos() {
        if (this.listaColaboradores.isSelectionEmpty()) {
            return false;
        }
        if (this.listaPropuestaProponente.isSelectionEmpty()) {
            return false;
        }
        if (this.campoMontoColab.getText().isBlank()) {
            return false;
        }
        if (Float.parseFloat(this.campoMontoColab.getText()) <= 0) {
            return false;
        }
        return true;
    }

    private void cargarRetornosCombo(List<TipoRetorno> retornos) {
        this.comboRetorno.removeAllItems();
        for (TipoRetorno r : retornos) {
            if (r == TipoRetorno.ENTRADA_GRATIS) {
                this.comboRetorno.addItem("Entradas gratis");
            }
            if (r == TipoRetorno.PORCENTAJE_GANANCIAS) {
                this.comboRetorno.addItem("Porcentaje de ganancias");
            }
        }
    }

    private void cargarImagenLabel(byte[] imagen) {
        if (imagen != null) {
            ByteArrayInputStream bais = new ByteArrayInputStream(imagen);
            try {
                BufferedImage temp = ImageIO.read(bais);
                Image imagenEscalada = temp.getScaledInstance(133, 133, Image.SCALE_SMOOTH);
                this.labelImagen.setIcon(new ImageIcon(imagenEscalada));
            } catch (IOException ex) {
                System.getLogger(RegistrarColaboracion.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        } else {
            this.labelImagen.setIcon(null);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDescripcion;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JTextField campoCategoria;
    private javax.swing.JTextField campoFechaPublicacion;
    private javax.swing.JTextField campoFechaRealizar;
    private javax.swing.JTextField campoLugar;
    private javax.swing.JFormattedTextField campoMontoColab;
    private javax.swing.JTextField campoMontoReunir;
    private javax.swing.JTextField campoPrecio;
    private javax.swing.JComboBox<String> comboRetorno;
    private javax.swing.JPanel datosPropuesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelFechaPublicacion;
    private javax.swing.JLabel labelFechaRealizar;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JLabel labelLugar;
    private javax.swing.JLabel labelMontoColab;
    private javax.swing.JLabel labelMontoReunir;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelRetorno;
    private javax.swing.JList<String> listaColaboradores;
    private javax.swing.JList<String> listaPropuestaProponente;
    // End of variables declaration//GEN-END:variables
}
