name: Pruebas con Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Comprobar el código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Instalar dependencias y ejecutar pruebas
        run: mvn clean test --batch-mode --no-transfer-progress

      - name: Publicar resultados de las pruebas
        uses: EnricoMi/publish-unit-test-result-action@v2.20.0
        with:
          trx_files: '**/target/test-*.xml'
